<?php
if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

add_shortcode( 'debicheck_form', 'debisure_render_form_shortcode' );

/**
 * Generate a unique account reference (e.g., DEBI-660F8A3B-1A2B)
 */
function debisure_generate_account_reference() {
    return 'DEBI-' . strtoupper( dechex( time() ) ) . '-' . strtoupper( wp_generate_password( 4, false, false ) );
}

function debisure_render_form_shortcode() {
    add_action( 'wp_footer', 'debisure_form_scripts' );

    $unique_reference = debisure_generate_account_reference();

    ob_start();
    ?>
    <div class="debisure-form-wrapper">
        <form id="debisure-dynamic-form" class="debisure-form">
            <div id="debisure-form-messages" style="margin-bottom: 15px;"></div>

            <!-- Autogenerated Unique Account Reference (Hidden from user view) -->
            <input type="hidden" id="deb_account_reference" name="accountReference" value="<?php echo esc_attr( $unique_reference ); ?>" />

            <div class="debisure-form-row">
                <label for="deb_mandate_name">Mandate Name</label>
                <input type="text" id="deb_mandate_name" name="mandateName" value="stephenleibbrandt" required />
            </div>

            <div class="debisure-form-row">
                <label for="deb_mandate_amount">Mandate Amount</label>
                <input type="number" id="deb_mandate_amount" name="mandateAmount" value="10" step="0.01" required />
            </div>

            <div class="debisure-form-row debisure-checkbox-row">
                <label>
                    <input type="checkbox" id="deb_is_individual" name="isIndividual" value="true" checked /> Is Individual
                </label>
            </div>

            <div class="debisure-form-row">
                <label for="deb_first_name">First Name</label>
                <input type="text" id="deb_first_name" name="firstName" value="Stephen" required />
            </div>

            <div class="debisure-form-row">
                <label for="deb_surname">Surname</label>
                <input type="text" id="deb_surname" name="surname" value="Smith" required />
            </div>

            <div class="debisure-form-row">
                <label for="deb_mobile_no">Mobile Number</label>
                <input type="text" id="deb_mobile_no" name="mobileNo" value="0741385922" required />
            </div>

            <div class="debisure-form-row">
                <label for="deb_email_address">Email Address</label>
                <input type="email" id="deb_email_address" name="emailAddress" value="stephen@caincomputing.co.za" required />
            </div>

            <div class="debisure-form-row">
                <label for="deb_debit_day">Debit Day</label>
                <select id="deb_debit_day" name="debitDay">
                    <option value="FirstDayOfMonth" selected>First Day Of Month</option>
                    <option value="LastDayOfMonth">Last Day Of Month</option>
                </select>
            </div>

            <div class="debisure-form-row">
                <label for="deb_december_debit_day">December Debit Day</label>
                <select id="deb_december_debit_day" name="decemberDebitDay">
                    <option value="FirstDayOfMonth" selected>First Day Of Month</option>
                    <option value="LastDayOfMonth">Last Day Of Month</option>
                </select>
            </div>

            <div class="debisure-form-submit-row">
                <button type="submit" id="debisure-submit-btn" class="debisure-submit-button">Submit Mandate</button>
            </div>
        </form>
    </div>
    <?php
    return ob_get_clean();
}

function debisure_form_scripts() {
    ?>
    <script type="text/javascript">
    document.addEventListener('DOMContentLoaded', function () {
        const form = document.getElementById('debisure-dynamic-form');
        if (!form) return;

        form.addEventListener('submit', function (e) {
            e.preventDefault();
            const submitBtn = document.getElementById('debisure-submit-btn');
            const msgBox = document.getElementById('debisure-form-messages');
            
            submitBtn.disabled = true;
            submitBtn.innerText = 'Submitting & Redirecting...';
            msgBox.innerHTML = '';

            const formData = {
                accountReference: document.getElementById('deb_account_reference').value,
                mandateName: document.getElementById('deb_mandate_name').value,
                mandateAmount: parseFloat(document.getElementById('deb_mandate_amount').value),
                isIndividual: document.getElementById('deb_is_individual').checked,
                firstName: document.getElementById('deb_first_name').value,
                surname: document.getElementById('deb_surname').value,
                mobileNo: document.getElementById('deb_mobile_no').value,
                emailAddress: document.getElementById('deb_email_address').value,
                debitDay: document.getElementById('deb_debit_day').value,
                decemberDebitDay: document.getElementById('deb_december_debit_day').value,
            };

            fetch('<?php echo esc_url( admin_url('admin-ajax.php?action=debisure_submit_form') ); ?>', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify(formData)
            })
            .then(response => response.json())
            .then(data => {
                if (data.success) {
                    const responseData = data.data;
                    
                    // Target mandateUrl nested inside data.data (as confirmed by the API return packet)
                    const redirectUrl = (responseData && responseData.data && responseData.data.mandateUrl) 
                                        || responseData.mandateUrl 
                                        || responseData.redirectUrl 
                                        || responseData.url;

                    if (redirectUrl) {
                        msgBox.innerHTML = '<div style="padding: 10px; background: #d4edda; color: #155724; border: 1px solid #c3e6cb;">Mandate created! Redirecting to payment gateway...</div>';
                        setTimeout(function() {
                            window.location.href = redirectUrl;
                        }, 1000);
                    } else {
                        submitBtn.disabled = false;
                        submitBtn.innerText = 'Submit Mandate';
                        msgBox.innerHTML = '<div style="padding: 10px; background: #fff3cd; color: #856404; border: 1px solid #ffeeba;">Mandate submitted, but no mandate URL was found in the response payload.</div>';
                        console.log('API Success Response Data:', responseData);
                    }
                } else {
                    submitBtn.disabled = false;
                    submitBtn.innerText = 'Submit Mandate';
                    msgBox.innerHTML = '<div style="padding: 10px; background: #f8d7da; color: #721c24; border: 1px solid #f5c6cb;">Error: ' + (data.data || 'Unknown error occurred.') + '</div>';
                }
            })
            .catch(error => {
                submitBtn.disabled = false;
                submitBtn.innerText = 'Submit Mandate';
                msgBox.innerHTML = '<div style="padding: 10px; background: #f8d7da; color: #721c24; border: 1px solid #f5c6cb;">Network error occurred. Please try again.</div>';
                console.error('Error:', error);
            });
        });
    });
    </script>
    <?php
}